### ISSUE TITLE
schizo

### ISSUE THREAD

**Issue by Magmafool** [ericpretzel/wid-bot#34]
hey guys
lets think about a new wid boit feature
what if
lets say
to think about it
we had a command that /schizopositng where if someone is doing something dumb you type their name and wid bot changes pfp and and nicknmane to some random person on the server and posts a random copypasta
@solarsido @my demons dislike inside out @$SHGO🚀🌙 @ppman17 @solarsido @nayeon the mental therapist @your demons @erakai @MasterWeasel @stuff expains @TheSpreadsheet_ @zhong xina
@solarsido @my demons dislike inside out @nayeon the mental therapist @ppman17 @solarsido @$SHGO🚀🌙 @erakai @MasterWeasel @stuff expains @TheSpreadsheet_ @zhong xina

**Comment by Magmafool** [comment]
hey guys
lets think about a new wid boit feature
what if
lets say
to think about it
we had a command that /schizopositng where if someone is doing something dumb you type their name and wid bot changes pfp and and nicknmane to some random person on the server and posts a random copypasta
@solarsido @my demons dislike inside out @$SHGO🚀🌙 @ppman17 @solarsido @nayeon the mental therapist @your demons @erakai @MasterWeasel @stuff expains @TheSpreadsheet_ @zhong xina
@solarsido @my demons dislike inside out @nayeon the mental therapist @ppman17 @solarsido @$SHGO🚀🌙 @erakai @MasterWeasel @stuff expains @TheSpreadsheet_ @zhong xina

**Comment by ericpretzel** [comment]
great idea
